spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/userService/**
        - id: goods-service
          uri: lb://goods-service
          predicates:
            - Path=/goodsService/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactionService/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
